apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: hello-python
spec:
  replicas: 4
  template:
    metadata:
      labels:
        app: hello-python
    spec:
      containers:
      - name: hello-python
        image: hello-python:latest
        imagePullPolicy: Never
        ports:
        - containerPort: 5000

# this is the deployment file
